#!/bin/sh
sed '/<!DOCTYPE/, /Adopt<\/td>/d' | \ 
sed '/<\/table>/, /<\/table>/d' | \
sed '/<\/tr>/,/<\/td>/d' | \
sed 's/<[^>]*>//g' | \
tr '`' "'" | \
sed 's/^ *//g' | \
sed 's/ *$//g' | \
sed '/^$/d' | \
sed "/[^pk'mnwlhaeiou]/Id" | \
tr '[:upper:]' '[:lower:]' | \
sort -u

